# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from time import sleep

driver = webdriver.Chrome()
  
driver.get("https://informesdeis.minsal.cl/SASVisualAnalytics/?reportUri=%2Freports%2Freports%2F0b3119f0-db06-4f10-a9cd-61092b5790bc&sectionIndex=0&sso_guest=true&reportViewOnly=true&reportContextBar=false&sas-welcome=false")
driver.set_window_size(1045, 671)

WebDriverWait(driver, 30).until(expected_conditions.frame_to_be_available_and_switch_to_it((By.ID,"VANextLogon_iframe")))

# we might crash the frontend as it takes too long to close the popup so we wait for two seconds
WebDriverWait(driver, 30).until(expected_conditions.presence_of_element_located((By.ID,"__dialog1-closeButton-BDI-content"))).click()
sleep(2)

# find the parent of the element with the text "Salud mental" and click it
WebDriverWait(driver, 30).until(expected_conditions.presence_of_element_located((By.XPATH,"//*[contains(text(), 'Salud mental')]/.."))).click()

# find the dropdowns with the region, servicio, comuna and establecimiento
# get all the values for each of the 4 dropdowns
# for each value, select it and wait for the table to load
# then, click the export button and wait for the download to finish

# open first drop-down
# get all options
WebDriverWait(driver, 30).until(expected_conditions.presence_of_element_located((By.ID,"__select0"))).click()
sleep(100)
regiones_list = driver.find_element(By.ID,"__list29")
print(regiones_list)
regiones = regiones_list.find_elements(By.TAG_NAME, "li")
print(regiones)

sleep(100)

